ccp/src/main/java/com/hbb20/CountryCodeAdapter.java
ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/java/com/hbb20/OnCountrySelectedListener.java

On country selected listener added

Added listener

---

ccp/src/main/java/com/hbb20/Country.java
ccp/src/main/res/raw/countries

change &apos; to escape single quote

---

ccp/build.gradle
ccp/src/main/java/com/hbb20/Country.java
ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/ukrainian.xml
ccp/src/main/res/values/attrs.xml

Added Ukrainian language translation.
Implemented correct sort for all locales.

Ukrainian language support

---

ccp/src/main/res/raw/a_new_lang_template.xml
ccp/src/main/res/raw/arabic.xml
ccp/src/main/res/raw/bengali.xml
ccp/src/main/res/raw/chinese_traditional.xml
ccp/src/main/res/raw/english.xml
ccp/src/main/res/raw/french.xml
ccp/src/main/res/raw/german.xml
ccp/src/main/res/raw/gujarati.xml
ccp/src/main/res/raw/hebrew.xml
ccp/src/main/res/raw/hindi.xml
ccp/src/main/res/raw/indonesia.xml
ccp/src/main/res/raw/japanese.xml
ccp/src/main/res/raw/korean.xml
ccp/src/main/res/raw/portuguese.xml
ccp/src/main/res/raw/russian.xml
ccp/src/main/res/raw/spanish.xml
ccp/src/main/res/raw/turkish.xml
ccp/src/main/res/raw/ukrainian.xml

Hi, Taiwan does not belong to China.

[update] language template setting of Taiwan

---

ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/italian.xml
ccp/src/main/res/values/attrs.xml

Adds support for italian language

Adds support for italian language

---

ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/farsi.xml
ccp/src/main/res/values/attrs.xml

I have added the Farsi(Persian) language to the project.

The Farsi language has been added to the project

---

ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/slovak.xml
ccp/src/main/res/values/attrs.xml

slovak language

---

app/build.gradle
build.gradle
ccp/build.gradle
gradle/wrapper/gradle-wrapper.properties

Reverts hbb20/CountryCodePickerProject#253

Revert "Android sdk 28"

---

ccp/src/main/res/raw/chinese_simplified.xml
ccp/src/main/res/raw/chinese_traditional.xml

I have some time after work to take a second look into this. And I spotted more places that are not accurate, which are corrected in this PR. There are changes both from chinese_simplified.xml and chinese_traditional.xml. Cheers.

More updates on chinese translations

---

app/build.gradle
ccp/build.gradle
ccp/src/main/res/raw/turkish.xml

Upgraded to build version 28.
"bir tür inek" is wrong translate. It will be "Guernsey Adası"

Wrong Translate and Upgraded to Build Version

---

app/src/main/res/layout/fragment_introduction.xml
ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/values/attrs.xml

I made this PR for
1. Set custom string for title, search hint, no result message

Add 3 custom attributes to ccpDialog 

---

ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/vietnamese.xml
ccp/src/main/res/values/attrs.xml

The translations were done by the translation team of our client, so they should be pretty accurate :).
We planning on releasing a new version of our app this week on Vietnam, so if we could get this merged and released would be fantastic :)
Thanks for this awesome library!

Add vietnamese language

---

ccp/src/main/res/raw/ccp_french.xml

First of all, thanks for the awesome project, saved us a ton of work in our app! :)
I just made a small change to the french translation to be closer to what a native would say.

Improve french translation

---

README.md
ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/ccp_kazakh.xml
ccp/src/main/res/raw/ccp_russian.xml
ccp/src/main/res/values/attrs.xml

Hello!
Please add a Kazakh language support as we need it in our project.
Thank you.

Kazakh language support

---

ccp/src/main/java/com/hbb20/CountryCodePicker.java

Allow setting the validity changed listener back to null

---

ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/layout/layout_code_picker.xml
ccp/src/main/res/layout/layout_full_width_code_picker.xml
ccp/src/main/res/values/attrs.xml
ccp/src/main/res/values/dimens.xml

Added ccp_padding property in attrs.xml to customize the cpp padding in custom inputs layouts.

add ccp_padding property

---

ccp/src/main/java/com/hbb20/CountryCodePicker.java

Hi. I appreciate your work. I'm using your library in my app and I want to pass country name as well as the flag resource id to an another Activity. I've noticed that you don't have a public api for such thing. So I did it. Maybe it will be helpful for other developer.

Add return selected country flag resource id.

---

README.md
ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/ccp_tagalog.xml
ccp/src/main/res/values/attrs.xml

The translations are from this [site](https://www.101languages.net/tagalog/country-names-tagalog/), and remaining countries are translated by one of my filipino colleague.

Added Tagalog/Filipino language support

---

ccp/build.gradle

- bump up libphonenumber-android version to support wider range of phone numbers

Dependency version update

---

README.md

hit count represent count of users that open repo

add hit count

---

README.md

add 
- star count badge 
- fork count badge
- license badge

add some shileds

---

ccp/src/main/res/values/strings.xml

Reverts hbb20/CountryCodePickerProject#458
Need to translate for all other languages.

Revert "Update strings.xml"

---

CHANGELOG.md
README.md
build.gradle
ccp/build.gradle
ccp/gradle.properties
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Required changes to publish to MavenCentral
Remove dependency from jCenter (use dependencies from mavenCentral)
Will miss you jCenter 😢

MavenCentral

---

ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/ccp_thai.xml
ccp/src/main/res/values/attrs.xml

-Add TH Language Support

---

app/src/main/res/layout/fragment_custom_color.xml
ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/ccp_basque.xml
ccp/src/main/res/raw/ccp_spanish.xml
ccp/src/main/res/values/attrs.xml

New language (BASQUE) and some fixes in the spanish translation.

New language (BASQUE) and some fixes in the spanish translation.

---

ccp/src/main/java/com/hbb20/CountryCodeDialog.java

Hello! I have tested this issue on 6 devices with Android versions from 6 until 12 everything works ok
lmk if you have different results on your end and hope on a merge with lib update :)

auto-open keyboard on dialog open

---

ccp/src/main/java/com/hbb20/CountryCodeAdapter.java
ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/layout/layout_code_picker.xml
ccp/src/main/res/layout/layout_full_width_code_picker.xml
ccp/src/main/res/layout/layout_recycler_country_tile.xml
ccp/src/main/res/values/attrs.xml

hello
use this xml code for enable or disable ripple when click to open dialog or choose county from recycle (true = enable , false = disable)
```
app:ccp_rippleEnable="true or false"
app:ccpDialog_rippleEnable="true or false"
```
Thank

ripple enable/disable feature added

---

ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/ccp_serbian.xml
ccp/src/main/res/values/attrs.xml

This PR adds Serbian language to the list of the supported languages

Adds Serbian language support

---

ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/tamil.xml
ccp/src/main/res/values/attrs.xml

Added files as per 
https://github.com/hbb20/CountryCodePickerProject/wiki/Add-New-Language-Support

Tamil language support

---

ccp/src/main/res/layout/layout_picker_dialog.xml
ccp/src/main/res/values/strings.xml

- fixed duplicate key issue while we use ccp library along with material design library.

fixed duplicate key issue

---

ccp/src/main/res/raw/ccp_portuguese.xml

Cingapura is wrong. In Portuguese it should be: Singapura

Update Cingapura  to Singapura in ccp_portuguese.xml

---

ccp/src/main/java/com/hbb20/CCPCountryGroup.java

Create group for +7 phone number

Create group for +7 phone number

---

ccp/src/main/java/com/hbb20/CountryCodePicker.java
ccp/src/main/res/raw/ccp_lithuanian.xml
ccp/src/main/res/values/attrs.xml

Add lithuanian language support
